openapi: 3.0.0
info:
  title: Sample User API
  description: A simple API to retrieve user information
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local server
paths:
  /users/{userId}:
    get:
      summary: Get a user by their ID
      description: Returns a single user
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A user object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
